version: '3.7'

services:
  # MYSQL
  mysqldb:
    platform: linux/amd64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    env_file:
      - ./docker/config/db/database.env
    volumes:
      - './docker/infra/mysql/log:/var/log/mysql'
    networks:
      - sf_app

  # Symfony App with PHP 8.1
  php:
    build:
      context: ./
    ports:
      - '9000:9000'
    restart: always
    volumes:
      - ./:/var/www/
    depends_on:
      - mysqldb
    networks:
      - sf_app

  # SERVER NGINX
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./docker/infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/infra/nginx/log/:/var/log/nginx
    depends_on:
      - mysqldb
      - php
    links:
      - php
    networks:
      - sf_app

  # ADMINER
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

networks:
  sf_app:

volumes:
    db-data:
